flask/project/models.py
# project/models.py


import datetime

from project import db, bcrypt


class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)

    def __init__(self, email, password, admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    def __repr__(self):
        return 'user email is {0}'.format(self.email)


class Email(db.Model):

    __tablename__ = 'emails'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String, unique=True, nullable=False)
    email_added_on = db.Column(db.DateTime, nullable=False)

    def __init__(self, email):
        self.email = email
        self.email_added_on = datetime.datetime.now()

flask/project/main/forms.py
# project/main/forms.py


from flask_wtf import Form
from wtforms import TextField
from wtforms.validators import DataRequired, Email, length


class SignUpForm(Form):
    email = TextField(
        'Enter your email address',
        validators=[DataRequired(), Email(), length(min=3)])

flask/project/user/forms.py
# project/user/forms.py


from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email


class LoginForm(Form):
    email = TextField('Email Address', [DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])

flask/project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask.ext.sqlalchemy import SQLAlchemy


################
#### config ####
################

app = Flask(__name__, static_folder='static')
app.config.from_object(os.environ['APP_SETTINGS'])


####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)


####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)


####################
#### flask-login ####
####################

from models import User

login_manager.login_view = "user.login"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500


@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403

flask/project/main/__init__.py
# project/users/__init__.py

flask/project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, request, flash, redirect, url_for

from forms import SignUpForm
from project import db
from project.models import Email


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################


@main_blueprint.route('/', methods=['GET', 'POST'])
def index():
    """Landing page for users to enter emails."""
    form = SignUpForm(request.form)
    if form.validate_on_submit():
        test = Email.query.filter_by(email=form.email.data).first()
        if test:
            flash('Sorry that email aleady exists!', 'danger')
        else:
            email = Email(email=form.email.data)
            db.session.add(email)
            db.session.commit()
            flash('Thank you for your interest!', 'success')
            return redirect(url_for('main.index'))
    return render_template('main/index.html', form=form)

flask/project/user/__init__.py
# project/user/__init__.py

flask/project/user/views.py
# project/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_user, logout_user, \
    login_required

from project import bcrypt
from project.models import User, Email
from project.user.forms import LoginForm


################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """Login page for admins."""
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('user.admin'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.index'))


@user_blueprint.route('/admin')
@login_required
def admin():
    """Displays submitted emails to the admin."""
    signups = Email.query.all()
    return render_template('user/admin.html', signups=signups)

flask/project/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flask-Landing{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>
  <body>

    {% include "navigation.html" %}

    <div class="container">

      <br>

      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
           {{message}}
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
      {% endwith %}

      <!-- child template -->
      {% block content %}{% endblock %}

      <br>

      <!-- errors -->
      {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
      {% endif %}

      <br>
      <hr>

      {% block footer %}
      <footer class="footer">
        <p>Copyright &copy; 2017 <a href="https://github.com/RuslanValeev">RuslanValeev</a>.</p>
      </footer>
      {% endblock %}

    </div>

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

flask/project/templates/main/index.html
{% extends "_base.html" %}
{% block title %} - Welcome{% endblock %}

{% block content %}

<div id="main">

  <!-- <h1>Sign up today to stay updated.</h1> -->
    <br>
    <div class="jumbotron">
      <h1 class="display-3">It's monitoring system!</h1>
      <p class="lead">Это система, позволяющая производить учет и анализ сетевого трафика обучающихся в сети интернет, при организации учебного процесса.</p>
      <hr class="my-4">
      <p>Войдите или зарегистрируйтесь, чтобы начать работу.</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </p>
    </div>
    <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ultricies justo sit amet tortor venenatis vehicula. Mauris tincidunt, lectus ac condimentum euismod, quam orci interdum elit, et congue ipsum lectus nec massa. Curabitur dapibus dui gravida, semper felis quis, sollicitudin sem. Donec lacinia fermentum risus a pharetra. Ut et consequat urna, non aliquet nisi.</p> -->
    <br>

  <!-- <form class="form-email" role="form" method="post" action="/">
    {{ form.csrf_token }}
    <p>
    {{ form.email.label }}
    <br>
    {{ form.email(placeholder="email@address.com") }}
    <span class="error">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
    </p>
    <button class="btn btn-success btn-sm" type="submit">Submit!</button>
  </form> -->

</div>

{% endblock %}

flask/project/templates/navigation.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Monitoring system</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        {% if current_user.is_authenticated() %}
          <li><a href="{{ url_for('user.admin') }}">Admin Page</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated() %}
          <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
        {% else %}
          <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Login</a></li>
        {% endif %}
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

flask/project/templates/user/admin.html
{% extends "_base.html" %}

{% block title %} - Signups{% endblock %}

{% block content %}

<h1>Настройте параметры и начните мониторинг</h1>

<br>

{% if signups %}
<!-- <table class="table admin_table">
  <tr><th>Email Address</th><th>Registered</th></tr>
  {% for signup in signups %}
  <tr><td>{{ signup.email }}</td><td>{{ signup.email_added_on }}</td></tr>
  {% endfor %}
</table> -->
{% else %}
  <p>No signups yet</p>
{% endif %}

{% endblock %}

flask/project/templates/user/login.html
{% extends "_base.html" %}

{% block title %} - Login{% endblock %}

{% block content %}

<h1>Please login</h1>
<br>
<form class="form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
  {{ form.email.label }}
  <br>
  {{ form.email(placeholder="email@address.com") }}
  <span class="error">
    {% if form.email.errors %}
      {% for error in form.email.errors %}
        {{ error }}
      {% endfor %}
    {% endif %}
  </span>
  </p>
  <p>
  {{ form.password.label }}
  <br>
  {{ form.password(placeholder="your password") }}
  <span class="error">
    {% if form.password.errors %}
      {% for error in form.password.errors %}
        {{ error }}
      {% endfor %}
    {% endif %}
  </span>
  </p>
  <button class="btn btn-success" type="submit">Sign in!</button>
</form>

{% endblock %}